- name: demo on variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: Print URL varaible
      ansible.builtin.debug:
        msg: "{{URL}}"


- name: demo on variables
  hosts: localhost
  tasks:
    - name: Print URL1 varaible
      ansible.builtin.debug:
        msg: "{{URL1}}"
      vars:
        URL1: sample.com
    - name: Print URL2 variable
      ansible.builtin.debug:
        msg: "{{URL2}}"
      vars:
        URL2: sample.com
