- name: demo on variables
  hosts: all
  Var:
   URL: sample.com
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
       msg: "{{ URL }}"

- name: demo on variables
  hosts: all
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      Vars:
        URL1: sample.com
    - name: print URL variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      Vars:
        URL2: sample.com

- name: register variable
  hosts: local host
  tasks:
    - name: uptime of the server
      ansible.builtin.shell: uptime
      register: OUT
    - name: print OUT var
      ansible.builtin.debug:
       msg: "{{ OUT }}"
