- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Print the linux
      ansible.builtin.debug:
        msg:  Hello, linux
      when: os_name == "linux"
    - name: print the unix
      ansible.builtin.debug:
        msg: hello, unix
      when: os_name == "unix"